CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Admins" (
    admin_id integer GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password text NOT NULL,
    phone character varying(20) NOT NULL,
    last_login timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY (admin_id)
);

CREATE TABLE "Companies" (
    company_id integer GENERATED BY DEFAULT AS IDENTITY,
    company_name character varying(150) NOT NULL,
    email character varying(100) NOT NULL,
    password text NOT NULL,
    address text NOT NULL,
    c_agent character varying(100) NOT NULL,
    c_information text NOT NULL,
    license_number character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY (company_id)
);

CREATE TABLE "Customers" (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY,
    policy_id integer,
    full_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password text NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    age integer NOT NULL,
    c_pancard character varying(20) NOT NULL,
    c_adhar character varying(20) NOT NULL,
    family_info text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY (customer_id)
);

CREATE TABLE "Agents" (
    agent_id integer GENERATED BY DEFAULT AS IDENTITY,
    company_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password text NOT NULL,
    phone character varying(20) NOT NULL,
    license_number character varying(50) NOT NULL,
    experience_years integer NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    pincode character varying(20) NOT NULL,
    profile_photo text NOT NULL,
    approved_status boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Agents" PRIMARY KEY (agent_id),
    CONSTRAINT "FK_Agents_Companies_company_id" FOREIGN KEY (company_id) REFERENCES "Companies" (company_id) ON DELETE RESTRICT
);

CREATE TABLE "InsuranceTypes" (
    type_id integer NOT NULL,
    company_id integer NOT NULL,
    type_name character varying(150) NOT NULL,
    description text NOT NULL,
    created_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    created_by character varying(100) NOT NULL,
    CONSTRAINT "PK_InsuranceTypes" PRIMARY KEY (type_id, company_id),
    CONSTRAINT "FK_InsuranceTypes_Companies_company_id" FOREIGN KEY (company_id) REFERENCES "Companies" (company_id) ON DELETE RESTRICT
);

CREATE TABLE "Queries" (
    query_id integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    subject character varying(200) NOT NULL,
    message text NOT NULL,
    send_date timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Queries" PRIMARY KEY (query_id),
    CONSTRAINT "FK_Queries_Customers_customer_id" FOREIGN KEY (customer_id) REFERENCES "Customers" (customer_id)
);

CREATE TABLE "InsurancePlans" (
    plan_id integer NOT NULL,
    company_id integer NOT NULL,
    type_id integer NOT NULL,
    agent_id integer,
    plan_name character varying(150) NOT NULL,
    premium_amount numeric NOT NULL,
    coverage_amount numeric NOT NULL,
    duration_months integer NOT NULL,
    description text NOT NULL,
    created_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT "PK_InsurancePlans" PRIMARY KEY (plan_id, company_id),
    CONSTRAINT "FK_InsurancePlans_Agents_agent_id" FOREIGN KEY (agent_id) REFERENCES "Agents" (agent_id),
    CONSTRAINT "FK_InsurancePlans_Companies_company_id" FOREIGN KEY (company_id) REFERENCES "Companies" (company_id) ON DELETE RESTRICT
);

CREATE TABLE "Policies" (
    policy_id integer GENERATED BY DEFAULT AS IDENTITY,
    policy_no character varying(50) NOT NULL,
    customer_id integer NOT NULL,
    agent_id integer,
    plan_id integer NOT NULL,
    company_id integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    policy_status character varying(20) NOT NULL,
    premium_amount numeric NOT NULL,
    created_by character varying(100) NOT NULL,
    CONSTRAINT "PK_Policies" PRIMARY KEY (policy_id),
    CONSTRAINT "FK_Policies_Agents_agent_id" FOREIGN KEY (agent_id) REFERENCES "Agents" (agent_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_Policies_Customers_customer_id" FOREIGN KEY (customer_id) REFERENCES "Customers" (customer_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_Policies_InsurancePlans_plan_id_company_id" FOREIGN KEY (plan_id, company_id) REFERENCES "InsurancePlans" (plan_id, company_id) ON DELETE RESTRICT
);

CREATE TABLE "Reviews" (
    review_id integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    plan_id integer NOT NULL,
    company_id integer NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY (review_id),
    CONSTRAINT "FK_Reviews_Customers_customer_id" FOREIGN KEY (customer_id) REFERENCES "Customers" (customer_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_InsurancePlans_plan_id_company_id" FOREIGN KEY (plan_id, company_id) REFERENCES "InsurancePlans" (plan_id, company_id) ON DELETE RESTRICT
);

CREATE TABLE "Payments" (
    payment_id integer GENERATED BY DEFAULT AS IDENTITY,
    policy_id integer NOT NULL,
    customer_id integer NOT NULL,
    amount numeric NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    method character varying(50) NOT NULL,
    payment_status character varying(20) NOT NULL,
    received_by_agent integer,
    CONSTRAINT "PK_Payments" PRIMARY KEY (payment_id),
    CONSTRAINT "FK_Payments_Agents_received_by_agent" FOREIGN KEY (received_by_agent) REFERENCES "Agents" (agent_id),
    CONSTRAINT "FK_Payments_Customers_customer_id" FOREIGN KEY (customer_id) REFERENCES "Customers" (customer_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_Payments_Policies_policy_id" FOREIGN KEY (policy_id) REFERENCES "Policies" (policy_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_Agents_company_id" ON "Agents" (company_id);

CREATE INDEX "IX_InsurancePlans_agent_id" ON "InsurancePlans" (agent_id);

CREATE INDEX "IX_InsurancePlans_company_id" ON "InsurancePlans" (company_id);

CREATE INDEX "IX_InsuranceTypes_company_id" ON "InsuranceTypes" (company_id);

CREATE INDEX "IX_Payments_customer_id" ON "Payments" (customer_id);

CREATE INDEX "IX_Payments_policy_id" ON "Payments" (policy_id);

CREATE INDEX "IX_Payments_received_by_agent" ON "Payments" (received_by_agent);

CREATE INDEX "IX_Policies_agent_id" ON "Policies" (agent_id);

CREATE INDEX "IX_Policies_customer_id" ON "Policies" (customer_id);

CREATE INDEX "IX_Policies_plan_id_company_id" ON "Policies" (plan_id, company_id);

CREATE INDEX "IX_Queries_customer_id" ON "Queries" (customer_id);

CREATE INDEX "IX_Reviews_customer_id" ON "Reviews" (customer_id);

CREATE INDEX "IX_Reviews_plan_id_company_id" ON "Reviews" (plan_id, company_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314082654_InitialCreate', '10.0.5');

COMMIT;

