CREATE TABLE "Admins" (
    "AdminId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" text NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "LastLogin" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("AdminId")
);


CREATE TABLE "AuditLogs" (
    "AuditLogId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActionType" character varying(50) NOT NULL,
    "EntityType" character varying(50) NOT NULL,
    "EntityId" integer NOT NULL,
    "PerformedBy" integer NOT NULL,
    "PerformedByName" character varying(100),
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("AuditLogId")
);


CREATE TABLE "Companies" (
    "CompanyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyName" character varying(150) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" text NOT NULL,
    "Address" text NOT NULL,
    "CAgent" character varying(100) NOT NULL,
    "CInformation" text NOT NULL,
    "LicenseNumber" character varying(50) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "InsuranceTypeId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("CompanyId")
);


CREATE TABLE "Customers" (
    "CustomerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PolicyId" integer,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" text NOT NULL,
    "Phone" character varying(20),
    "Address" text,
    "City" character varying(100),
    "Age" integer NOT NULL,
    "Dob" timestamp with time zone NOT NULL,
    "CPancard" character varying(20),
    "CAdhar" character varying(20),
    "FamilyInfo" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "VerificationStatus" character varying(20) NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId")
);


CREATE TABLE "InsuranceTypes" (
    "TypeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TypeName" character varying(150) NOT NULL,
    "Description" text,
    "Icon" character varying(100),
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InsuranceTypes" PRIMARY KEY ("TypeId")
);


CREATE TABLE "UserDocuments" (
    "DocumentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserType" character varying(20) NOT NULL,
    "UserId" integer NOT NULL,
    "Category" character varying(100) NOT NULL,
    "DocumentName" character varying(150) NOT NULL,
    "FileUrl" text NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FileSize" bigint NOT NULL,
    "Status" character varying(20) NOT NULL,
    "RejectionReason" text,
    "ReviewedBy" integer,
    "UploadedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    CONSTRAINT "PK_UserDocuments" PRIMARY KEY ("DocumentId")
);


CREATE TABLE "Advertisements" (
    "AdId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "PlanId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "BannerUrl" text,
    "AmountPaid" numeric NOT NULL,
    "DurationDays" integer NOT NULL,
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Advertisements" PRIMARY KEY ("AdId"),
    CONSTRAINT "FK_Advertisements_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "Agents" (
    "AgentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" text NOT NULL,
    "Phone" character varying(20),
    "LicenseNumber" character varying(50),
    "ExperienceYears" integer NOT NULL,
    "Address" text,
    "City" character varying(100),
    "Pincode" character varying(20),
    "ProfilePhoto" text,
    "Dob" timestamp with time zone NOT NULL,
    "Aadhaar" character varying(20),
    "Pan" character varying(20),
    "ApprovedStatus" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "VerificationStatus" character varying(20) NOT NULL,
    CONSTRAINT "PK_Agents" PRIMARY KEY ("AgentId"),
    CONSTRAINT "FK_Agents_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "Queries" (
    "QueryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Phone" character varying(20),
    "Subject" character varying(200),
    "Message" text,
    "SendDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Queries" PRIMARY KEY ("QueryId"),
    CONSTRAINT "FK_Queries_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId")
);


CREATE TABLE "AdPayments" (
    "AdPaymentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "AdvertisementId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "PaymentStatus" character varying(20) NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AdPayments" PRIMARY KEY ("AdPaymentId"),
    CONSTRAINT "FK_AdPayments_Advertisements_AdvertisementId" FOREIGN KEY ("AdvertisementId") REFERENCES "Advertisements" ("AdId") ON DELETE CASCADE,
    CONSTRAINT "FK_AdPayments_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "ChatMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "AgentId" integer NOT NULL,
    "SenderType" character varying(20) NOT NULL,
    "MessageText" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("AgentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_ChatMessages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "CustomerAgentMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "AgentId" integer NOT NULL,
    "SenderType" character varying(20) NOT NULL,
    "MessageText" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CustomerAgentMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CustomerAgentMessages_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("AgentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_CustomerAgentMessages_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT
);


CREATE TABLE "InsurancePlans" (
    "PlanId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "TypeId" integer NOT NULL,
    "AgentId" integer,
    "PlanName" character varying(150) NOT NULL,
    "PremiumAmount" numeric NOT NULL,
    "CoverageAmount" numeric NOT NULL,
    "DurationMonths" integer NOT NULL,
    "Description" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    CONSTRAINT "PK_InsurancePlans" PRIMARY KEY ("PlanId", "CompanyId"),
    CONSTRAINT "FK_InsurancePlans_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("AgentId"),
    CONSTRAINT "FK_InsurancePlans_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "Policies" (
    "PolicyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PolicyNo" character varying(50) NOT NULL,
    "CustomerId" integer NOT NULL,
    "AgentId" integer,
    "PlanId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "PolicyStatus" character varying(20) NOT NULL,
    "PremiumAmount" numeric NOT NULL,
    "CreatedBy" character varying(100),
    CONSTRAINT "PK_Policies" PRIMARY KEY ("PolicyId"),
    CONSTRAINT "FK_Policies_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("AgentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Policies_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Policies_InsurancePlans_PlanId_CompanyId" FOREIGN KEY ("PlanId", "CompanyId") REFERENCES "InsurancePlans" ("PlanId", "CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "PolicyRequests" (
    "RequestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "AgentId" integer NOT NULL,
    "PlanId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "Status" character varying(20) NOT NULL,
    "RejectionReason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    CONSTRAINT "PK_PolicyRequests" PRIMARY KEY ("RequestId"),
    CONSTRAINT "FK_PolicyRequests_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("AgentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_PolicyRequests_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
    CONSTRAINT "FK_PolicyRequests_InsurancePlans_PlanId_CompanyId" FOREIGN KEY ("PlanId", "CompanyId") REFERENCES "InsurancePlans" ("PlanId", "CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "Reviews" (
    "ReviewId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "PlanId" integer NOT NULL,
    "CompanyId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_InsurancePlans_PlanId_CompanyId" FOREIGN KEY ("PlanId", "CompanyId") REFERENCES "InsurancePlans" ("PlanId", "CompanyId") ON DELETE RESTRICT
);


CREATE TABLE "Payments" (
    "PaymentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PolicyId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Method" character varying(50),
    "PaymentStatus" character varying(20) NOT NULL,
    "ReceivedByAgent" integer,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
    CONSTRAINT "FK_Payments_Agents_ReceivedByAgent" FOREIGN KEY ("ReceivedByAgent") REFERENCES "Agents" ("AgentId"),
    CONSTRAINT "FK_Payments_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payments_Policies_PolicyId" FOREIGN KEY ("PolicyId") REFERENCES "Policies" ("PolicyId") ON DELETE RESTRICT
);


CREATE INDEX "IX_AdPayments_AdvertisementId" ON "AdPayments" ("AdvertisementId");


CREATE INDEX "IX_AdPayments_CompanyId" ON "AdPayments" ("CompanyId");


CREATE INDEX "IX_Advertisements_CompanyId" ON "Advertisements" ("CompanyId");


CREATE INDEX "IX_Agents_CompanyId" ON "Agents" ("CompanyId");


CREATE INDEX "IX_ChatMessages_AgentId" ON "ChatMessages" ("AgentId");


CREATE INDEX "IX_ChatMessages_CompanyId" ON "ChatMessages" ("CompanyId");


CREATE INDEX "IX_CustomerAgentMessages_AgentId" ON "CustomerAgentMessages" ("AgentId");


CREATE INDEX "IX_CustomerAgentMessages_CustomerId" ON "CustomerAgentMessages" ("CustomerId");


CREATE INDEX "IX_InsurancePlans_AgentId" ON "InsurancePlans" ("AgentId");


CREATE INDEX "IX_InsurancePlans_CompanyId" ON "InsurancePlans" ("CompanyId");


CREATE INDEX "IX_Payments_CustomerId" ON "Payments" ("CustomerId");


CREATE INDEX "IX_Payments_PolicyId" ON "Payments" ("PolicyId");


CREATE INDEX "IX_Payments_ReceivedByAgent" ON "Payments" ("ReceivedByAgent");


CREATE INDEX "IX_Policies_AgentId" ON "Policies" ("AgentId");


CREATE INDEX "IX_Policies_CustomerId" ON "Policies" ("CustomerId");


CREATE INDEX "IX_Policies_PlanId_CompanyId" ON "Policies" ("PlanId", "CompanyId");


CREATE INDEX "IX_PolicyRequests_AgentId" ON "PolicyRequests" ("AgentId");


CREATE INDEX "IX_PolicyRequests_CustomerId" ON "PolicyRequests" ("CustomerId");


CREATE INDEX "IX_PolicyRequests_PlanId_CompanyId" ON "PolicyRequests" ("PlanId", "CompanyId");


CREATE INDEX "IX_Queries_CustomerId" ON "Queries" ("CustomerId");


CREATE INDEX "IX_Reviews_CustomerId" ON "Reviews" ("CustomerId");


CREATE INDEX "IX_Reviews_PlanId_CompanyId" ON "Reviews" ("PlanId", "CompanyId");


