// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartInsuranceHub.Data;

#nullable disable

namespace SmartInsuranceHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartInsuranceHub.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AdminId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("admin_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FullName");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastLogin");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.HasKey("admin_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Agent", b =>
                {
                    b.Property<int>("agent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AgentId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("agent_id"));

                    b.Property<string>("address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<bool>("approved_status")
                        .HasColumnType("boolean")
                        .HasColumnName("ApprovedStatus");

                    b.Property<string>("city")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("City");

                    b.Property<int>("company_id")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<int>("experience_years")
                        .HasColumnType("integer")
                        .HasColumnName("ExperienceYears");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FullName");

                    b.Property<string>("license_number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("pincode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Pincode");

                    b.Property<string>("profile_photo")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhoto");

                    b.HasKey("agent_id");

                    b.HasIndex("company_id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.ChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("agent_id")
                        .HasColumnType("integer")
                        .HasColumnName("AgentId");

                    b.Property<int>("company_id")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<string>("message_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MessageText");

                    b.Property<string>("sender_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SenderType");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SentAt");

                    b.HasKey("id");

                    b.HasIndex("agent_id");

                    b.HasIndex("company_id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("company_id"));

                    b.Property<string>("address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<string>("c_agent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CAgent");

                    b.Property<string>("c_information")
                        .HasColumnType("text")
                        .HasColumnName("CInformation");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("license_number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.HasKey("company_id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customer_id"));

                    b.Property<string>("address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<int>("age")
                        .HasColumnType("integer")
                        .HasColumnName("Age");

                    b.Property<string>("c_adhar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CAdhar");

                    b.Property<string>("c_pancard")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CPancard");

                    b.Property<string>("city")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("City");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("family_info")
                        .HasColumnType("text")
                        .HasColumnName("FamilyInfo");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FullName");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<int?>("policy_id")
                        .HasColumnType("integer")
                        .HasColumnName("PolicyId");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.HasKey("customer_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.InsurancePlan", b =>
                {
                    b.Property<int>("plan_id")
                        .HasColumnType("integer")
                        .HasColumnName("PlanId")
                        .HasColumnOrder(1);

                    b.Property<int>("company_id")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId")
                        .HasColumnOrder(2);

                    b.Property<int?>("agent_id")
                        .HasColumnType("integer")
                        .HasColumnName("AgentId");

                    b.Property<decimal>("coverage_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("CoverageAmount");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("duration_months")
                        .HasColumnType("integer")
                        .HasColumnName("DurationMonths");

                    b.Property<string>("plan_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("PlanName");

                    b.Property<decimal>("premium_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("PremiumAmount");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<int>("type_id")
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    b.HasKey("plan_id", "company_id");

                    b.HasIndex("agent_id");

                    b.HasIndex("company_id");

                    b.ToTable("InsurancePlans");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.InsuranceType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("type_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Icon");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("TypeName");

                    b.HasKey("type_id");

                    b.ToTable("InsuranceTypes");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Payment", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PaymentId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("payment_id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric")
                        .HasColumnName("Amount");

                    b.Property<int>("customer_id")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    b.Property<string>("method")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Method");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PaymentDate");

                    b.Property<string>("payment_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PaymentStatus");

                    b.Property<int>("policy_id")
                        .HasColumnType("integer")
                        .HasColumnName("PolicyId");

                    b.Property<int?>("received_by_agent")
                        .HasColumnType("integer")
                        .HasColumnName("ReceivedByAgent");

                    b.HasKey("payment_id");

                    b.HasIndex("customer_id");

                    b.HasIndex("policy_id");

                    b.HasIndex("received_by_agent");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Policy", b =>
                {
                    b.Property<int>("policy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PolicyId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("policy_id"));

                    b.Property<int?>("agent_id")
                        .HasColumnType("integer")
                        .HasColumnName("AgentId");

                    b.Property<int>("company_id")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<string>("created_by")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CreatedBy");

                    b.Property<int>("customer_id")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<int>("plan_id")
                        .HasColumnType("integer")
                        .HasColumnName("PlanId");

                    b.Property<string>("policy_no")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PolicyNo");

                    b.Property<string>("policy_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PolicyStatus");

                    b.Property<decimal>("premium_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("PremiumAmount");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.HasKey("policy_id");

                    b.HasIndex("agent_id");

                    b.HasIndex("customer_id");

                    b.HasIndex("plan_id", "company_id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Query", b =>
                {
                    b.Property<int>("query_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("QueryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("query_id"));

                    b.Property<int?>("customer_id")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("message")
                        .HasColumnType("text")
                        .HasColumnName("Message");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<DateTime>("send_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SendDate");

                    b.Property<string>("subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Subject");

                    b.HasKey("query_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Review", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReviewId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("review_id"));

                    b.Property<string>("comment")
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<int>("company_id")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("customer_id")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    b.Property<int>("plan_id")
                        .HasColumnType("integer")
                        .HasColumnName("PlanId");

                    b.Property<int>("rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.HasKey("review_id");

                    b.HasIndex("customer_id");

                    b.HasIndex("plan_id", "company_id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Agent", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.ChatMessage", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("agent_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInsuranceHub.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.InsurancePlan", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("agent_id");

                    b.HasOne("SmartInsuranceHub.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Payment", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInsuranceHub.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("policy_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInsuranceHub.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("received_by_agent");

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Policy", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("agent_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartInsuranceHub.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInsuranceHub.Models.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("plan_id", "company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Query", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartInsuranceHub.Models.Review", b =>
                {
                    b.HasOne("SmartInsuranceHub.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInsuranceHub.Models.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("plan_id", "company_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("InsurancePlan");
                });
#pragma warning restore 612, 618
        }
    }
}
